apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  labels:
    spiffe.io/spire-managed-identity: 'true'
  name: client
spec:
  initContainers:
    - args:
        - -config
        - /etc/spiffe-helper/helper.conf
      restartPolicy: Always
      startupProbe:
        exec:
          command:
            - stat
            - /opt/client-certs/svid.pem  
        initialDelaySeconds: 1
        periodSeconds: 2
        failureThreshold: 15
      image: registry.redhat.io/zero-trust-workload-identity-manager/spiffe-helper-rhel9:v0.10.0
      name: spiffe-helper
      resources: {}
      securityContext:
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: /spiffe-workload-api
          name: spiffe-workload-api
          readOnly: true
        - mountPath: /opt/client-certs
          name: client-certs
        - mountPath: /etc/spiffe-helper
          name: spiffe-helper
  config:
    extensions:
      oidc:
        issuer_url: https://oidc-discovery.apps.central.example.com
        audience: "opentelemetry-collector"
        username_claim: "sub"
        issuer_ca_path: /etc/certs/oidc/ca.crt
    exporters:
      debug:
        sampling_initial: 5
        sampling_thereafter: 200
        verbosity: detailed
      otlp_http/ztwim:
        endpoint: https://server-collector:4318
        retry_on_failure:
          enabled: true
        tls:
          ca_file: /opt/client-certs/svid_bundle.pem
          cert_file: /opt/client-certs/svid.pem
          key_file: /opt/client-certs/svid.key
        headers:
          "x-spiffe-id": "spiffe://${env:TRUST_DOMAIN}/ns/${env:POD_NAMESPACE}/sa/${env:POD_SA_NAME}"
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            tls:
              ca_file: /opt/client-certs/svid_bundle.pem
              cert_file: /opt/client-certs/svid.pem
              client_ca_file: /opt/client-certs/svid_bundle.pem
              key_file: /opt/client-certs/svid.key
              max_version: '1.3'
              min_version: '1.3'
              reload_interval: 1m
            include_metadata: true
      otlp/protected:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14317
            tls:
              ca_file: /opt/client-certs/svid_bundle.pem
              cert_file: /opt/client-certs/svid.pem
              client_ca_file: /opt/client-certs/svid_bundle.pem
              key_file: /opt/client-certs/svid.key
              max_version: '1.3'
              min_version: '1.3'
              reload_interval: 1m
            include_metadata: true
            auth:
              authenticator: oidc
    processors:
      attributes/spiffe:
        actions:
          - key: peer.spiffe_id
            from_context: metadata.x-spiffe-id
            action: upsert
      resource/svid:
        attributes:
          - key: subject
            action: upsert
            from_context: auth.claims.sub
    service:
      extensions:
        - oidc
      pipelines:
        logs:
          exporters:
            - otlp_http/ztwim
            - debug
          processors:
            - attributes/spiffe
            - resource/svid
          receivers:
            - otlp
            - otlp/protected
        metrics:
          exporters:
            - otlp_http/ztwim
            - debug
          processors:
            - attributes/spiffe
            - resource/svid
          receivers:
            - otlp
            - otlp/protected
        traces:
          exporters:
            - otlp_http/ztwim
            - debug
          processors:
            - attributes/spiffe
            - resource/svid
          receivers:
            - otlp
            - otlp/protected
      telemetry:
        logs:
          level: info
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
  configVersions: 1
  daemonSetUpdateStrategy: {}
  deploymentUpdateStrategy: {}
  env:
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_SA_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: TRUST_DOMAIN
      valueFrom:
          configMapKeyRef:
            name: spiffe-trust-domain
            key: TRUST_DOMAIN
  ingress:
    route: {}
  ipFamilyPolicy: SingleStack
  managementState: managed
  mode: deployment
  networkPolicy:
    enabled: true
  observability:
    metrics:
      enableMetrics: true
  podAnnotations:
    kubectl.kubernetes.io/default-container: otc-container
  podDnsConfig: {}
  replicas: 1
  resources: {}
  targetAllocator:
    allocationStrategy: consistent-hashing
    collectorNotReadyGracePeriod: 30s
    collectorTargetReloadInterval: 30s
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  upgradeStrategy: automatic
  volumeMounts:
    - mountPath: /opt/client-certs
      name: client-certs
    - mountPath: /etc/certs/oidc
      name: oidc-ca
  volumes:
    - csi:
        driver: csi.spiffe.io
        readOnly: true
      name: spiffe-workload-api
    - emptyDir:
        medium: Memory
      name: client-certs
    - configMap:
        defaultMode: 420
        name: spiffe-helper
      name: spiffe-helper
    - configMap:
        defaultMode: 420
        name: spiffe-trust-domain
      name: spiffe-trust-domain
    - secret:
        secretName: apps-central-example-com-wildcard-certificate
      name: oidc-ca
