apiVersion: v1
kind: Service
metadata:
  name: splunk-hec
  namespace: openshift-logging
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - appProtocol: https
      name: admin
      port: 8000
      protocol: TCP
      targetPort: 8000
    - appProtocol: https
      name: hec
      port: 8088
      protocol: TCP
      targetPort: 8088
    - appProtocol: https
      name: api
      port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: splunk-hec
  sessionAffinity: None
  type: ClusterIP
