{
 "title": "Resource flapping",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resource",
    "query": {
     "query": "query_result(k8s_resource_flapping_total{})"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "query_result(k8s_resource_flapping_total{})"
    }
   },
   { "name": "topkmax", "query": "25" }
  ]
 },
 "panels": [
  {
   "title": "High frequent changes",
   "type": "piechart",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topkmax, sum by (resource_name, resource_type) (count_over_time(k8s_resource_flapping_total{replica=\"0\",resource_name=~\"$resource\",resource_type!~\"(events|leases)\"}[$__range:1m])) > 5)",
     "legendFormat": "{{resource_name}}/{{resource_type}}"
    }
   ]
  },
  {
   "title": "User to verb",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topkmax, sum by (source_user, verb) (count_over_time(k8s_resource_flapping_total{replica=\"0\",source_user=~\"$user\",resource_name=~\"$resource\"}[$__range:1m])))",
     "legendFormat": "{{source_user}}/{{verb}}"
    }
   ]
  },
  {
   "title": "User to Resource",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topkmax, sum by (source_user, resource_name, resource_type) (count_over_time(k8s_resource_flapping_total{replica=\"0\",source_user=~\"$user\",resource_name=~\"$resource\"}[$__range:1m])))",
     "legendFormat": "{{source_user}}/{{resource_name}}/{{resource_type}}"
    }
   ]
  }
 ]
}