apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otc
  namespace: otcaddcontainers
spec:
  config:
    exporters:
      debug:
        sampling_initial: 5
        sampling_thereafter: 200
        verbosity: detailed
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"
    service:
      pipelines:
        logs:
          exporters:
            - debug
          receivers:
            - otlp
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
  configVersions: 1
  additionalContainers:
  - name: debug
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli
    command: ["/bin/sh", "-c"]
    args:
      - |
        trap "exit 0" SIGTERM SIGINT;
        while true; do sleep 10 & wait $!; done
  daemonSetUpdateStrategy: {}
  deploymentUpdateStrategy: {}
  ingress:
    route: {}
  ipFamilyPolicy: SingleStack
  managementState: managed
  mode: deployment
  networkPolicy:
    enabled: true
  observability:
    metrics: {}
  podDnsConfig: {}
  replicas: 1
  resources: {}
  targetAllocator:
    allocationStrategy: consistent-hashing
    collectorNotReadyGracePeriod: 30s
    collectorTargetReloadInterval: 30s
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  upgradeStrategy: automatic
  podAnnotations:
    kubectl.kubernetes.io/default-container: otc-container
