apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: ottl
  namespace: otcottl
spec:
  config:
    exporters:
      debug:
        sampling_initial: 5
        sampling_thereafter: 200
        verbosity: detailed
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
    processors:
      transform/envs:
        log_statements:
          - context: log
            statements:
              - set(log.attributes["k8s.node.name"], "${KUBE_NODE_NAME}")
              - set(log.attributes["k8s.cluster.name"], "${CLUSTER_NAME}")
        metric_statements:
          - context: datapoint
            statements:
              - set(datapoint.attributes["k8s.node.name"], "${KUBE_NODE_NAME}")
              - set(datapoint.attributes["k8s.cluster.name"], "${CLUSTER_NAME}")
        trace_statements:
          - context: span
            statements:
              - set(span.attributes["k8s.node.name"], "${KUBE_NODE_NAME}")
              - set(span.attributes["k8s.cluster.name"], "${CLUSTER_NAME}")
    service:
      pipelines:
        logs:
          exporters:
            - debug
          processors:
            - transform/envs
          receivers:
            - otlp
        metrics:
          exporters:
            - debug
          processors:
            - transform/envs
          receivers:
            - otlp
        traces:
          exporters:
            - debug
          processors:
            - transform/envs
          receivers:
            - otlp
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
  env:
  - name: KUBE_NODE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: spec.nodeName
  - name: CLUSTER_NAME
    value: "testing"
  configVersions: 1
  daemonSetUpdateStrategy: {}
  deploymentUpdateStrategy: {}
  ingress:
    route: {}
  ipFamilyPolicy: SingleStack
  managementState: managed
  mode: deployment
  networkPolicy:
    enabled: true
  observability:
    metrics: {}
  podDnsConfig: {}
  replicas: 1
  resources: {}
  targetAllocator:
    allocationStrategy: consistent-hashing
    collectorNotReadyGracePeriod: 30s
    collectorTargetReloadInterval: 30s
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  upgradeStrategy: automatic
  podAnnotations:
    kubectl.kubernetes.io/default-container: otc-container
