apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opentelemetry-targetallocator-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opentelemetry-targetallocator-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: otctargetallocator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opentelemetry-targetallocator-role
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
      - probes
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
