apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-server
  namespace: otccerts
spec:
  additionalContainers:
    - args:
        - trap "exit 0" SIGTERM SIGINT; while true; do sleep 10 & wait $!; done
      command:
        - /bin/sh
        - -c
      image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9bd872f8adc3138f7c3bd8267aa1a8ecb5cd2e7f3385b8434a684cfd52093909
      name: debug
      resources: {}
  config:
    exporters:
      debug:
        sampling_initial: 5
        sampling_thereafter: 200
        verbosity: detailed
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            tls:
              ca_file: /etc/certs/server/ca.crt
              cert_file: /etc/certs/server/tls.crt
              client_ca_file: /etc/certs/server/ca.crt
              key_file: /etc/certs/server/tls.key
              max_version: '1.3'
              min_version: '1.3'
              reload_interval: 1m
          http:
            endpoint: 0.0.0.0:4318
            tls:
              ca_file: /etc/certs/server/ca.crt
              cert_file: /etc/certs/server/tls.crt
              client_ca_file: /etc/certs/server/ca.crt
              key_file: /etc/certs/server/tls.key
              max_version: '1.3'
              min_version: '1.3'
              reload_interval: 1m
    service:
      pipelines:
        logs:
          exporters:
            - debug
          receivers:
            - otlp
        metrics:
          exporters:
            - debug
          receivers:
            - otlp
        traces:
          exporters:
            - debug
          receivers:
            - otlp
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
  configVersions: 3
  daemonSetUpdateStrategy: {}
  deploymentUpdateStrategy: {}
  ingress:
    route: {}
  ipFamilyPolicy: SingleStack
  managementState: managed
  mode: deployment
  networkPolicy:
    enabled: true
  observability:
    metrics: {}
  podDnsConfig: {}
  replicas: 1
  resources: {}
  targetAllocator:
    allocationStrategy: consistent-hashing
    collectorNotReadyGracePeriod: 30s
    collectorTargetReloadInterval: 30s
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  upgradeStrategy: automatic
  volumeMounts:
    - mountPath: /etc/certs/server
      name: server-certs
      readOnly: true
  volumes:
    - name: server-certs
      secret:
        defaultMode: 256
        items:
          - key: ca.crt
            path: ca.crt
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
        secretName: otc-server
  podAnnotations:
    kubectl.kubernetes.io/default-container: otc-container
